module Main where

import Test.Hspec

import qualified Auth.AnthropicOAuthSpec
import qualified Core.TypesSpec
import qualified Core.ErrorsSpec
import qualified Core.ConfigSpec
import qualified Security.SecretsSpec
import qualified Security.PolicySpec
import qualified Security.PathSpec
import qualified Security.CommandSpec
import qualified Handles.LogSpec
import qualified Handles.FileSpec
import qualified Handles.ShellSpec
import qualified Handles.NetworkSpec
import qualified Handles.MemorySpec
import qualified Handles.ChannelSpec
import qualified Providers.ClassSpec
import qualified Agent.AgentDefSpec
import qualified Agent.CompletionSpec
import qualified Agent.ContextSpec
import qualified Providers.AnthropicSpec
import qualified Agent.LoopSpec
import qualified Channels.CLISpec
import qualified CLI.CommandsSpec
import qualified CLI.ConfigSpec
import qualified CLI.ImportSpec
import qualified Tools.RegistrySpec
import qualified Tools.ShellSpec
import qualified Tools.FileReadSpec
import qualified Tools.GitSpec
import qualified Tools.MemorySpec
import qualified Tools.EditSpec
import qualified Tools.ProcessSpec
import qualified Handles.ProcessSpec
import qualified Tools.WebSearchSpec
import qualified Tools.MessageSpec
import qualified Tools.CronSpec
import qualified Tools.ImageSpec
import qualified Memory.NoneSpec
import qualified Memory.MarkdownSpec
import qualified Memory.SQLiteSpec
import qualified Agent.MemorySpec
import qualified Agent.CompactionSpec
import qualified Agent.ContextTrackerSpec
import qualified Agent.SlashCommandsSpec
import qualified Providers.OpenAISpec
import qualified Providers.OllamaSpec
import qualified Providers.OpenRouterSpec
import qualified Security.CryptoSpec
import qualified Security.PairingSpec
import qualified Security.VaultAgeSpec
import qualified Security.VaultPassphraseSpec
import qualified Security.VaultPluginSpec
import qualified Security.VaultSpec
import qualified Gateway.AuthSpec
import qualified Gateway.RoutesSpec
import qualified Gateway.ServerSpec
import qualified Channels.ClassSpec
import qualified Channels.TelegramSpec
import qualified Channels.SignalSpec
import qualified Channels.SignalTransportSpec
import qualified Agent.IdentitySpec
import qualified Scheduler.CronSpec
import qualified Scheduler.HeartbeatSpec
import qualified Integration.SignalFlowSpec
import qualified Integration.CLISpec
import qualified Integration.ImportRoundTripSpec
import qualified Transcript.TypesSpec
import qualified Handles.TranscriptSpec
import qualified Handles.HarnessSpec
import qualified Harness.ClaudeCodeSpec
import qualified Harness.TmuxSpec
import qualified Transcript.CombinatorSpec
import qualified Transcript.ProviderSpec
import qualified Session.TypesSpec

main :: IO ()
main = hspec $ do
  describe "Auth.AnthropicOAuth" Auth.AnthropicOAuthSpec.spec
  describe "Core.Types" Core.TypesSpec.spec
  describe "Core.Errors" Core.ErrorsSpec.spec
  describe "Core.Config" Core.ConfigSpec.spec
  describe "Security.Secrets" Security.SecretsSpec.spec
  describe "Security.Policy" Security.PolicySpec.spec
  describe "Security.Path" Security.PathSpec.spec
  describe "Security.Command" Security.CommandSpec.spec
  describe "Handles.Log" Handles.LogSpec.spec
  describe "Handles.File" Handles.FileSpec.spec
  describe "Handles.Shell" Handles.ShellSpec.spec
  describe "Handles.Network" Handles.NetworkSpec.spec
  describe "Handles.Memory" Handles.MemorySpec.spec
  describe "Handles.Channel" Handles.ChannelSpec.spec
  describe "Providers.Class" Providers.ClassSpec.spec
  describe "Agent.AgentDef" Agent.AgentDefSpec.spec
  describe "Agent.Context" Agent.ContextSpec.spec
  describe "Agent.Completion" Agent.CompletionSpec.spec
  describe "Providers.Anthropic" Providers.AnthropicSpec.spec
  describe "Agent.Loop" Agent.LoopSpec.spec
  describe "Channels.CLI" Channels.CLISpec.spec
  describe "CLI.Commands" CLI.CommandsSpec.spec
  describe "CLI.Config" CLI.ConfigSpec.spec
  describe "CLI.Import" CLI.ImportSpec.spec
  describe "Tools.Registry" Tools.RegistrySpec.spec
  describe "Tools.Shell" Tools.ShellSpec.spec
  describe "Tools.FileRead" Tools.FileReadSpec.spec
  describe "Tools.Git" Tools.GitSpec.spec
  describe "Tools.Memory" Tools.MemorySpec.spec
  describe "Tools.Edit" Tools.EditSpec.spec
  describe "Tools.Process" Tools.ProcessSpec.spec
  describe "Handles.Process" Handles.ProcessSpec.spec
  describe "Tools.WebSearch" Tools.WebSearchSpec.spec
  describe "Tools.Message" Tools.MessageSpec.spec
  describe "Tools.Cron" Tools.CronSpec.spec
  describe "Tools.Image" Tools.ImageSpec.spec
  describe "Memory.None" Memory.NoneSpec.spec
  describe "Memory.Markdown" Memory.MarkdownSpec.spec
  describe "Memory.SQLite" Memory.SQLiteSpec.spec
  describe "Agent.Memory" Agent.MemorySpec.spec
  describe "Agent.Compaction" Agent.CompactionSpec.spec
  describe "Agent.ContextTracker" Agent.ContextTrackerSpec.spec
  describe "Agent.SlashCommands" Agent.SlashCommandsSpec.spec
  describe "Providers.OpenAI" Providers.OpenAISpec.spec
  describe "Providers.Ollama" Providers.OllamaSpec.spec
  describe "Providers.OpenRouter" Providers.OpenRouterSpec.spec
  describe "Security.Crypto" Security.CryptoSpec.spec
  describe "Security.Pairing" Security.PairingSpec.spec
  describe "Security.VaultAge" Security.VaultAgeSpec.spec
  describe "Security.VaultPassphrase" Security.VaultPassphraseSpec.spec
  describe "Security.VaultPlugin" Security.VaultPluginSpec.spec
  describe "Security.Vault" Security.VaultSpec.spec
  describe "Gateway.Auth" Gateway.AuthSpec.spec
  describe "Gateway.Routes" Gateway.RoutesSpec.spec
  describe "Gateway.Server" Gateway.ServerSpec.spec
  describe "Channels.Class" Channels.ClassSpec.spec
  describe "Channels.Telegram" Channels.TelegramSpec.spec
  describe "Channels.Signal" Channels.SignalSpec.spec
  describe "Channels.Signal.Transport" Channels.SignalTransportSpec.spec
  describe "Agent.Identity" Agent.IdentitySpec.spec
  describe "Scheduler.Cron" Scheduler.CronSpec.spec
  describe "Scheduler.Heartbeat" Scheduler.HeartbeatSpec.spec
  describe "Integration.SignalFlow" Integration.SignalFlowSpec.spec
  describe "Integration.CLI" Integration.CLISpec.spec
  describe "Integration.ImportRoundTrip" Integration.ImportRoundTripSpec.spec
  describe "Transcript.Types" Transcript.TypesSpec.spec
  describe "Handles.Transcript" Handles.TranscriptSpec.spec
  describe "Handles.Harness" Handles.HarnessSpec.spec
  describe "Harness.ClaudeCode" Harness.ClaudeCodeSpec.spec
  describe "Harness.Tmux" Harness.TmuxSpec.spec
  describe "Transcript.Combinator" Transcript.CombinatorSpec.spec
  describe "Transcript.Provider" Transcript.ProviderSpec.spec
  describe "Session.Types" Session.TypesSpec.spec
