module Main where

import Test.Hspec

import qualified Core.TypesSpec
import qualified Core.ErrorsSpec
import qualified Core.ConfigSpec
import qualified Security.SecretsSpec
import qualified Security.PolicySpec
import qualified Security.PathSpec
import qualified Security.CommandSpec
import qualified Handles.LogSpec
import qualified Handles.FileSpec
import qualified Handles.ShellSpec
import qualified Handles.NetworkSpec
import qualified Handles.MemorySpec
import qualified Handles.ChannelSpec
import qualified Providers.ClassSpec
import qualified Agent.ContextSpec
import qualified Providers.AnthropicSpec
import qualified Agent.LoopSpec
import qualified Channels.CLISpec
import qualified CLI.CommandsSpec
import qualified Tools.RegistrySpec
import qualified Tools.ShellSpec
import qualified Tools.FileReadSpec
import qualified Tools.GitSpec
import qualified Tools.MemorySpec
import qualified Memory.NoneSpec
import qualified Memory.MarkdownSpec
import qualified Memory.SQLiteSpec
import qualified Agent.MemorySpec
import qualified Providers.OpenAISpec
import qualified Providers.OllamaSpec
import qualified Providers.OpenRouterSpec
import qualified Security.CryptoSpec
import qualified Security.PairingSpec
import qualified Gateway.AuthSpec
import qualified Gateway.RoutesSpec
import qualified Gateway.ServerSpec

main :: IO ()
main = hspec $ do
  describe "Core.Types" Core.TypesSpec.spec
  describe "Core.Errors" Core.ErrorsSpec.spec
  describe "Core.Config" Core.ConfigSpec.spec
  describe "Security.Secrets" Security.SecretsSpec.spec
  describe "Security.Policy" Security.PolicySpec.spec
  describe "Security.Path" Security.PathSpec.spec
  describe "Security.Command" Security.CommandSpec.spec
  describe "Handles.Log" Handles.LogSpec.spec
  describe "Handles.File" Handles.FileSpec.spec
  describe "Handles.Shell" Handles.ShellSpec.spec
  describe "Handles.Network" Handles.NetworkSpec.spec
  describe "Handles.Memory" Handles.MemorySpec.spec
  describe "Handles.Channel" Handles.ChannelSpec.spec
  describe "Providers.Class" Providers.ClassSpec.spec
  describe "Agent.Context" Agent.ContextSpec.spec
  describe "Providers.Anthropic" Providers.AnthropicSpec.spec
  describe "Agent.Loop" Agent.LoopSpec.spec
  describe "Channels.CLI" Channels.CLISpec.spec
  describe "CLI.Commands" CLI.CommandsSpec.spec
  describe "Tools.Registry" Tools.RegistrySpec.spec
  describe "Tools.Shell" Tools.ShellSpec.spec
  describe "Tools.FileRead" Tools.FileReadSpec.spec
  describe "Tools.Git" Tools.GitSpec.spec
  describe "Tools.Memory" Tools.MemorySpec.spec
  describe "Memory.None" Memory.NoneSpec.spec
  describe "Memory.Markdown" Memory.MarkdownSpec.spec
  describe "Memory.SQLite" Memory.SQLiteSpec.spec
  describe "Agent.Memory" Agent.MemorySpec.spec
  describe "Providers.OpenAI" Providers.OpenAISpec.spec
  describe "Providers.Ollama" Providers.OllamaSpec.spec
  describe "Providers.OpenRouter" Providers.OpenRouterSpec.spec
  describe "Security.Crypto" Security.CryptoSpec.spec
  describe "Security.Pairing" Security.PairingSpec.spec
  describe "Gateway.Auth" Gateway.AuthSpec.spec
  describe "Gateway.Routes" Gateway.RoutesSpec.spec
  describe "Gateway.Server" Gateway.ServerSpec.spec
